# Basic
title: Jessie.Y's Den
subtitle: A blog for recoding life in pieces
welcome_message: WELCOME TO OUR WORLD 
description: Arvin.W, another owner.

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

# The blog button should not be removed.
blog_button:
    title: 博客
    description: Visit blog

markdown: kramdown
# Navigation buttons in the front page.
#nav:
    # - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate, jekyll-ga]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: jessiewy
    # duoshuo:
    # uyan: 2136055 
    
# Social
social:
    weibo: arvin
    github: jessiewy
    twitter: hustarvin
    #gplus: 107108267983477358170
    mail: hustxnwsg@gmail.com

# Google Analytics
ga:
    id: UA-101993059-1
    host: jessiewy.github.io

exclude:
    BlogAnalytics-af397259503c.json

jekyll_ga:
  service_account_email: blogpvstatistics@bloganalytics-172605.iam.gserviceaccount.com # service account email address
  key_file: BlogAnalytics-d99a4bd910e2.p12  # service account private key file
  key_secret: notasecret    # service account private key's password
  profileID: ga:154312497        # profile ID 
  start: last month         # Beginning of report
  end: now                  # End of report
  metric: ga:pageviews      # Metric code
  segment:                  # optional
  filters:                  # optional
  sort: true                # Sort posts by this metric

jekyll_ga:
  sort: false
jekyll_sort:
  - src: posts
    by: _ga
    direction: down
    dest: posts_popular 
