# Basic
title: Jessie.Y's Den
subtitle: A blog for recoding life in pieces
welcome_message: WELCOME TO OUR WORLD 
description: Arvin.W, another owner.

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

# The blog button should not be removed.
blog_button:
    title: 博客
    description: Visit blog

markdown: kramdown
# Navigation buttons in the front page.
#nav:
    # - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: jessiewy
    # duoshuo:
    # uyan: 2136055 
    
# Social
social:
    weibo: arvin
    github: jessiewy
    twitter: hustarvin
    #gplus: 107108267983477358170
    mail: hustxnwsg@gmail.com

# Google Analytics
ga:
    id: UA-101993059-1
    host: https://jessiewy.github.io/
